### PR TITLE
Pypi release

### PR DESCRIPTION
**Pull request by avivajpeyi**
- Partially set up CI for automated release (**need permissions to add in security tokens to complete the release process!**) 
- Add `changelog.md` to document changes in this release
- Add `contributing.md` to document steps to do a release (and other contributing info)

### CODE REVIEW

**Comment by avivajpeyi** [comment]
I realise now that there are contributing notes on the README.md, I think the main thing in these contributing notes are the instructions for the release.

**Comment by tzdwi** [comment]
Is this ready to go? Also, I like having the more explicit CoC + release instructions all together!

**Comment by avivajpeyi** [comment]
Hey this is ready to go! I need this in master to set up the release :)

**Comment by avivajpeyi** [comment]
As pointed out by @athulvis , [jazzhands](https://pypi.org/project/jazzhands/) is taken. 
Some suggestions for this projects' pypi release were:

- `jazz-hands`
- `jazzhands-wavelets`

which one should we go for? BTW note that this is just for the `pip` install. To import you'd still do `import jazzhands`

**Comment by tzdwi** [comment]
Merged!

**Pull request merged**
