### PR TITLE
Changed Wavelets from function to class type

### PR DESCRIPTION
**Pull request by theand9**
I haven't tested the code ++ getters, setters left.

### CODE REVIEW

**Comment by tzdwi** [comment]
I'm getting a bug when I try 

```python
nu_lo = 1/20
nu_hi = 1

log_omega_lo = np.log2(2*np.pi*nu_lo)
log_omega_hi = np.log2(2*np.pi*nu_hi)

omegas = np.logspace(log_omega_lo, log_omega_hi, 50, base=2)
taus = np.linspace(0, baseline, 100)

t_obs, f_obs = np.genfromtxt('one_sin_0p05_noise_100_obs.txt', unpack=True)

wav = Wavelet([phi_1,phi_2,phi_3],phi_1,f_obs,t_obs,omegas,taus)
test_wwz, test_wwa = wav.compute_wavelet()
```

Looks like there's a name error:
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-e36d498b7cfc> in <module>
----> 1 test_wwz, test_wwa = wav.compute_wavelet()

~/Research/UW/JazzHands/jazzhands/wavelets.py in compute_wavelet(exclude, parallel, n_processes)
    368 
    369         else:
--> 370             transform = np.array([[self._wavelet_transform(tau, omega)]
    371                                   for omega in self.omegas
    372                                   for tau in tqdm(self.taus)])

NameError: name 'self' is not defined
```

**Comment by theand9** [comment]
That's weird. Looking into it

**Comment by tzdwi** [comment]
Also, small request: can we change the name of the class to something like `WaveletTransformer` or something like that? It would leave room for us to write a separate `Wavelet` class that has it's own methods for weighing points, and choosing basis functions. If you're not a fan, that's totally ok too.

**Comment by theand9** [comment]
Squashed all bugs

**Comment by tzdwi** [comment]
Looks like there's an array shape bug. The resulting arrays have shape `(1,len(omegas)*len(taus))`, and they should be  `(len(omegas),len(taus))`. Even after reshaping, they're still something gone wonky (plots attached; wwz1 is the version calculated with the old code, test_wwz is the new version).
Screen Shot 2020-09-08 at 4 04 58 PM

**Comment by tzdwi** [comment]
I think I figured it out. Replacing  
```python
transform = np.array([[self._wavelet_transform(exclude, tau, omega)]
                                      for omega in self._omegas  for tau in tqdm(self._taus)])
```
with
```python
transform = np.array(
                [[self._wavelet_transform(exclude, tau, omega) for omega in self._omegas]
                 for tau in self._taus])	
```
in `WaveletTransformer.compute_wavelet` does the trick.

**Comment by tzdwi** [comment]
Works perfectly! Nice fix. Also didn't say above, but nice job on the whole class and the getter/setter methods.

**Comment by theand9** [comment]
Thanks!!

**Pull request merged**
