### PR TITLE
API update and scale convention

### PR DESCRIPTION
**Pull request by tzdwi**
This is a work-in-progress pull request that is going to update some of the API, and add support for users who are familiar with different wavelet conventions. In summary:

1. The syntax for `WaveletTransform.__init__` has been updated so the user will, at minimum only need to set the time and data arrays. The intention is that users who are unfamiliar with the Foster (1996) math will be able to initialize a `WaveletTransformer` object, and just tell it to compute the wavelet transform (and let the code figure out the correct omegas and taus).

2. If users give omegas and taus when initializing `WaveletTransformer`, or at any time update those quantities, the `WaveletTransformer` will automatically set its new `_scales` and `_nus` attributes, which are the Torrence & Compo scale and actual frequency respectively. Similarly, users can initialize `WaveletTransformer` with scales, or nus, and the other quantities will update.

3. Added optional input to `WaveletTransformer.compute_wavelet` for users to specify taus, as well as omegas/scales/nus at runtime. TODO: add an `auto_compute` method that does not take those inputs, and automatically generates them.

### CODE REVIEW

**Comment by tzdwi** [comment]
Updated the setter methods to not require that arrays are the same shape

**Comment by tzdwi** [comment]
Implemented new `auto_compute` method. Added functions from `frequency_grid.py` to `WaveletTransformer`.

 Closes #6

**Comment by theand9** [comment]
Heyy, just went through the PR and I found some bugs, I'll send a commit to solve them. 
Also, could you update the docstring for the auto_compute, as it's a little confusing

**Comment by tzdwi** [comment]
Just fixed the docstring for auto_compute; let me know if it's clear enough.

**Comment by tzdwi** [comment]
Also merged in #16 to this PR; figured the docs should go with the new API.

**Pull request merged**
